module.exports=[{
    Job:"1",
    Position:"Data Operator",
    Company:"BAXTER",
    Location:"Bengaluru,Karnataka",
    Salary:"40,000-50,000",
    
 },
   {
    Job:"2",
    Position:"Senior Account Executive",
    Company:"Abra Outsourcing Private Limited",
    Location:"Thiruchirapalli,TamilNadu",
    Salary:"30,000-40,000",
},
{
    Job:"3",
    Position:"Online Bidder",
    Company:"SEO DISCOVERY Private Limited",
    Location:"Mohali,Punjab",
    Salary:"20,000-40,000",
},
{
    Job:"4",
    Position:"Content Writer",
    Company:"WlogPress.tech",
    Location:"Delhi",
    Salary:"30,000-52,000",
},
{
    Job:"5",
    Position:"Sr.Executive-HR",
    Company:"ISOTECH Corporation",
    Location:"Ahmedabad,Gujarat",
    Salary:"25,000-35,000",
},
{
    Job:"6",
    Position:"E-Commerce Specialist",
    Company:"WOODOLOGY INDIA",
    Location:"Delhi",
    Salary:"15,000-30,000",
},
{
    Job:"7",
    Position:"Online Bidder",
    Company:"Bussiness Websort Private Limited",
    Location:"Ludiyana,Punjab",
    Salary:"8,000-20,000",
},
{
    Job:"8",
    Position:"Junior Bussiness Analyst",
    Company:"Go Green Private Limited",
    Location:"Vellacheri,chennai",
    Salary:"30,000-40,000",
},
{
    Job:"9",
    Position:"Tender Executive",
    Company:"Sky Force Limited",
    Location:"Mumbai",
    Salary:"20,000-40,000",
},
{
    Job:"10",
    Position:"Graphics Designer",
    Company:"Darshan Soft-Tech Limited",
    Location:"Coimbatore,TamilNadu",
    Salary:"35,000-40,000",
},
{
    Job:"11",
    Position:"Placement Officer",
    Company:"IREZ Acadamey",
    Location:"Cochi,Kerala",
    Salary:"30,000-40,000",
},
{
    Job:"12",
    Position:"Bussiness Development Executive",
    Company:"Puretech Internet",
    Location:"Mohali,Punjab",
    Salary:"35,000-60,000",
},
{
    Job:"13",
    Position:"Content Writer",
    Company:"KAAR Technology",
    Location:"Vellore,TamilNadu",
    Salary:"25,000-40,000",
},
{
    Job:"14",
    Position:"Graphics Designer",
    Company:"Sanjay Software Private Limited",
    Location:"Coimbatore,TamilNadu",
    Salary:"55,000-80,000",
},
{
    Job:"15",
    Position:"UI/UX Designer",
    Company:"TCS Private Limited",
    Location:"Bengaluru,Karnataka",
    Salary:"35,000-60,000",
}]